/**
 * agentNames.ts — canonical `agent` values written by the v2 Analysts
 * (CLAUDE.md "Agent architecture — 6 Analysts" table) plus the synthetic
 * cross-agent-pattern agent.
 *
 * Phase D/E `detect()` functions for each Analyst MUST set `agent` to one of
 * these constants and prefix `finding.id` per the conventions documented
 * next to each one below — `actionMeta.ts` and `crossAgentPatterns.ts` match
 * on these prefixes.
 */

export const AGENTS = {
  /** Performance & Budget Analyst — bidding, scaling, general (CLAUDE.md). */
  PERFORMANCE_BUDGET: "performance_budget_analyst",
  /** Quality & Structure Analyst — structure, copy, landing_page. */
  QUALITY_STRUCTURE: "quality_structure_analyst",
  /** Audience & Copy Analyst — audience, copy, brand. */
  AUDIENCE_COPY: "audience_copy_analyst",
  /** Search Intelligence Analyst — keywords, structure, audience. */
  SEARCH_INTELLIGENCE: "search_intelligence_analyst",
  /** Market Intelligence Analyst — competitive, brand, general, pmax. */
  MARKET_INTELLIGENCE: "market_intelligence_analyst",
  /** Landing Page Scorer — landing_page, copy. */
  LANDING_PAGE: "landing_page_scorer",
  /** Synthetic findings generated by crossAgentPatterns.ts during synthesis. */
  SYNTHESIS_PATTERN: "synthesis_pattern",
} as const;

export type AgentName = (typeof AGENTS)[keyof typeof AGENTS];

/**
 * finding.id prefix conventions (used by actionMeta.ts / crossAgentPatterns.ts):
 *
 *   PERFORMANCE_BUDGET:
 *     "budget-locked-<id>"   — campaign losing IS to budget cap, headroom to raise
 *     "idle-budget-<id>"     — campaign under-spending its budget
 *     "rank-locked-<id>"     — campaign losing IS to rank (QS/bid), not budget
 *     "cpa-overage-<id>"     — campaign CPA over target by RULE_CPA_OVERAGE_RATIO
 *     "roas-shortfall-<id>"  — campaign ROAS under target by RULE_ROAS_SHORTFALL_RATIO
 *
 *   SEARCH_INTELLIGENCE:
 *     "add-negative-<id>"        — search term(s) to add as negatives
 *     "new-keyword-<id>"         — converting search term to promote to a keyword
 *     "search-term-pattern-<id>" — broader structural pattern across search terms
 *
 *   AUDIENCE_COPY:
 *     "low-ctr-ad-<id>"   — ad CTR below ad-group median (RULE_AD_CTR_FLOOR_RATIO)
 *     "audience-<id>"     — RLSA / Customer Match / lookalike opportunity
 *
 *   QUALITY_STRUCTURE:
 *     "low-qs-<id>"    — keyword QS at/below RULE_QS_MAX with material spend
 *     "structure-<id>" — account structure issue (ad group/keyword density, etc.)
 *     "extension-<id>" — missing/under-used ad extensions
 *
 *   LANDING_PAGE:
 *     "landing-page-<id>" — landing page scoring issue
 *
 *   SYNTHESIS_PATTERN:
 *     "sp-rank-cpa-trap-<targetId>"   — rank-locked + cpa-overage on same campaign
 *     "sp-budget-misalloc-<runDate>"  — idle-budget donor(s) + budget-locked receiver(s)
 *     "sp-copy-qs-systemic-<runDate>" — account-wide low-CTR ads + low expected-CTR keywords
 */
